# Generated by Django 4.1.1 on 2022-10-05 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woman', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='women',
            old_name='time_published',
            new_name='is_published',
        ),
    ]
